server:
    dev: "mgmt-rev2.team.healthstream.com"
    qa: "10.11.8.120/STS"
    prod: ""
token_url: "/STS/connect/accesstokenvalidation"
token_validation_url: "/STS/connect/accesstokenvalidation"
student_group_url: "/CSG/api/StudentGroup"
client_id: "juice-app"
 

    
